### ISSUE TITLE
Prototype mismatch warning

### ISSUE THREAD

**Issue by nfg** [jberger/Mock-MonkeyPatch#3]
Hello!

I use Mock::MonkeyPatch a lot at $WORK, but I have a problem mocking functions exported by Dancer2 plugins. Basically, Dancer2 exports those functions with the prototype `(@)`, so when I try patching them, I get a warning like

```
Prototype mismatch: sub MyApp::test: none vs (@) at /home/nfg/prototype-warning/local/lib/perl5/Mock/MonkeyPatch.pm line 4.
```

I tried calling `no warnings "prototype";` before creating the mock object, but that doesn't affect warnings inside Mock::MonkeyPatch.

**Comment by jberger** [comment]
In essence, what you should be doing is passing in a sub with the appropriate prototype. In the case of `(@)` it is basically the same thing, but if the user were using some other more useful prototype, like `(\@)` or `(&@)` or `(_)` giving it a sub with the incorrect prototype will change the behavior, possibly dramatically. I have to think about what the right thing to do here is.

**Comment by jberger** [comment]
And now that I've refreshed my memory, the user provides the sub which is then wrapped by one from the library. So I think probably, my wrapper sub should be prototyped. The question is, should it be prototyped the same as the replacement given or the original? I'm going to have to think about **that** a bit.

**Comment by jberger** [comment]
I'm going to go with the idea that the installed mock is going to get the same prototype as the function being mocked. It really is the only thing that makes sense. As a result the arguments passed to the provided mock will be the same as what the original function would have been, again, making the most sense I think.

**Comment by nfg** [comment]
It works! Thank you so much :grinning:
